// flow-typed signature: 0a91bb4721d390fc30b1c929227d25d0
// flow-typed version: <<STUB>>/isomorphic-ws_v^4.0.1/flow_v0.166.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-ws/browser' {
  declare module.exports: any;
}

declare module 'isomorphic-ws/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-ws/browser.js' {
  declare module.exports: $Exports<'isomorphic-ws/browser'>;
}
declare module 'isomorphic-ws/node.js' {
  declare module.exports: $Exports<'isomorphic-ws/node'>;
}
